# Generated by Django 5.2.13 on 2026-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_user_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
